# Generated by Django 6.0.4 on 2026-04-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('symbol', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mass', models.DecimalField(decimal_places=4, max_digits=10)),
                ('category', models.CharField(choices=[('nonmetal', 'Nonmetal'), ('noble-gas', 'Noble Gas'), ('alkali-metal', 'Alkali Metal'), ('alkaline-earth-metal', 'Alkaline Earth Metal'), ('metalloid', 'Metalloid'), ('halogen', 'Halogen'), ('post-transition-metal', 'Post-transition Metal'), ('transition-metal', 'Transition Metal'), ('lanthanide', 'Lanthanide'), ('actinide', 'Actinide')], max_length=50)),
                ('electrons', models.JSONField()),
                ('discovery', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(max_length=7)),
                ('config', models.CharField(max_length=100)),
                ('radius', models.IntegerField()),
                ('ionization', models.FloatField(blank=True, null=True)),
                ('electronegativity', models.FloatField(blank=True, null=True)),
                ('period', models.IntegerField()),
                ('group', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField()),
            ],
        ),
    ]
